### ISSUE TITLE
motdgd won't send new ad to player

### ISSUE THREAD

**Issue by RoboMWM** [MOTDgd-Ltd/sourcemod-plugin#2]
Seems like this occurs when a player saw an motdgd ad before in their motd. On the client, they just see the "thanks for watching" message (not exact quote).

Using Team Fortress 2, MOTDgd Adverts 2.5.32. I also just installed a fresh new server hence why I noticed this (this likely is occurring in my other server as well), so I'm using the latest stable sourcemod and metamod versions as of today (yes I know, I'll get the SM and MM versions if they're actually needed...)

```
L 10/16/2017 - 19:25:34: [SM] Exception reported: HTTPRequestHandle invalid, not yet sent or invalid buffer size
L 10/16/2017 - 19:25:34: [SM] Blaming: motdgd_adverts.smx
L 10/16/2017 - 19:25:34: [SM] Call stack trace:
L 10/16/2017 - 19:25:34: [SM]   [0] Steam_GetHTTPResponseBodyData
L 10/16/2017 - 19:25:34: [SM]   [1] Line 491, include/EasyHTTP.inc::EasyHTTP_SteamToolsComplete
```

**Comment by motdgd** [comment]
Thanks for reporting this issue, however it looks to be related to the ongoing Team Fortress 2 problem which Valve needs to fix, we can't do so sadly.

**Comment by RoboMWM** [comment]
So this announcement is not actually true then? http://steamcommunity.com/groups/motdgd#announcements/detail/1438190618779600769

**Comment by motdgd** [comment]
Nope, we put it back in place due to ongoing issues but it looks like it's now resolved as of the recent major update.

**Comment by Glubbable** [comment]
I hate to bump this, but it appears there's been a misunderstanding about this problem.

This is an error that only occurs in SteamTools. It seems that if you use the SteamWorks method of doing this job, the error does not occur and the client gets the MOTD as intended.

Since SteamTools no longer gets updated and that SteamWorks is the only SteamAPI extension that's still getting support from some of the SM devs. I suggest promoting the recommendation of using SteamWorks over SteamTools for this plugin.

However, I have only done a small scale test, which so far has shown the issue is resolved from the short term perspective. I will post an update about the long term soonish or whenever the error resurfaces (I am hopeful it doesn't).
